// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvgG4tBganeTrIKnQxrmKqjWoLng_oMlQ',
    appId: '1:269869397651:web:672f18e72d5266b8beff66',
    messagingSenderId: '269869397651',
    projectId: 'cogito-efce7',
    authDomain: 'cogito-efce7.firebaseapp.com',
    databaseURL: 'https://cogito-efce7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cogito-efce7.appspot.com',
    measurementId: 'G-MPLQVB0VEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQfW4PjpOa-UG3cLq7VObfXPOx1RNhlQs',
    appId: '1:269869397651:android:b73a86a82c1ac040beff66',
    messagingSenderId: '269869397651',
    projectId: 'cogito-efce7',
    databaseURL: 'https://cogito-efce7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cogito-efce7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD17pxUc929b9L5NhGBXlcf23QXoZDTyDU',
    appId: '1:269869397651:ios:8664408a90810343beff66',
    messagingSenderId: '269869397651',
    projectId: 'cogito-efce7',
    databaseURL: 'https://cogito-efce7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cogito-efce7.appspot.com',
    iosBundleId: 'com.cogitodev.org.cogito2boilerplate',
  );

}